apiVersion: apps/v1
kind: Deployment
metadata:
  name: screenshot-crawler
  namespace: cloudeon
  labels:
    app: screenshot-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screenshot-crawler
  template:
    metadata:
      labels:
        app: screenshot-crawler
    spec:
      containers:
      - name: screenshot-crawler
        image: xxx.cloudeon.top/peterpoker/screenshot-crawler
        imagePullPolicy: Always
        ports:
        - containerPort: 7860
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: screenshot-crawler
  namespace: cloudeon
  labels:
    app: screenshot-crawler
spec:
  type: NodePort
  ports:
    - port: 7860
      targetPort: 7860
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: screenshot-crawler