apiVersion: v1
kind: Secret
metadata:
  name: gradio-auth
  namespace: cloudeon
type: Opaque
stringData:
  username: admin
  password: admin
  openai_api_key: your-api-key
  openai_api_base: https://dashscope.aliyuncs.com/compatible-mode/v1/
  openai_model: deepseek-v3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: screenshot-crawler
  namespace: cloudeon
  labels:
    app: screenshot-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screenshot-crawler
  template:
    metadata:
      labels:
        app: screenshot-crawler
    spec:
      containers:
      - name: screenshot-crawler
        image: xxx.cloudeon.top/peterpoker/screenshot-crawler
        imagePullPolicy: Always
        env:
        - name: GRADIO_USERNAME
          valueFrom:
            secretKeyRef:
              name: gradio-auth
              key: username
        - name: GRADIO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradio-auth
              key: password
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradio-auth
              key: openai_api_key
        - name: OPENAI_API_BASE
          valueFrom:
            secretKeyRef:
              name: gradio-auth
              key: openai_api_base
        - name: OPENAI_MODEL
          valueFrom:
            secretKeyRef:
              name: gradio-auth
              key: openai_model
        ports:
        - containerPort: 7860
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: screenshot-crawler
  namespace: cloudeon
  labels:
    app: screenshot-crawler
spec:
  type: NodePort
  ports:
    - port: 7860
      targetPort: 7860
      nodePort: 30198
      protocol: TCP
      name: http
  selector:
    app: screenshot-crawler